# Generated by Django 4.0.3 on 2022-03-04 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Info', 'verbose_name_plural': 'Info'},
        ),
        migrations.AlterModelOptions(
            name='infotranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Info Translation'},
        ),
    ]
