# Generated by Django 4.0.3 on 2022-03-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_info_options_alter_infotranslation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_img',
            field=models.ImageField(default='asdfasdfasdf', upload_to='product_pics'),
            preserve_default=False,
        ),
    ]
