# Generated by Django 4.0.3 on 2022-03-12 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_product_imgs_remove_project_imgs_projectimgs_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Каталог', 'verbose_name_plural': 'Каталоги'},
        ),
        migrations.AlterModelOptions(
            name='categorytranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Каталог Translation'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Сертификат', 'verbose_name_plural': 'Сертификаты'},
        ),
        migrations.AlterModelOptions(
            name='characteristic',
            options={'verbose_name': 'характеристика', 'verbose_name_plural': 'характеристика'},
        ),
        migrations.AlterModelOptions(
            name='characteristictranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'характеристика Translation'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='infotranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Контакты Translation'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='productimgs',
            options={'verbose_name': 'Изображение продукта', 'verbose_name_plural': 'Изображения продукта'},
        ),
        migrations.AlterModelOptions(
            name='producttranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Товар Translation'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='projectimgs',
            options={'verbose_name': 'картина', 'verbose_name_plural': 'фотографий'},
        ),
        migrations.AlterModelOptions(
            name='projecttranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Проект Translation'},
        ),
        migrations.RemoveField(
            model_name='brand',
            name='link',
        ),
        migrations.AlterField(
            model_name='brand',
            name='img',
            field=models.ImageField(upload_to='brand_pics', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(upload_to='category_pics', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='img',
            field=models.ImageField(upload_to='certificate_pics', verbose_name='Сертификат'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='characteristictranslation',
            name='key',
            field=models.CharField(max_length=50, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='characteristictranslation',
            name='value',
            field=models.CharField(max_length=50, null=True, verbose_name='значение'),
        ),
        migrations.AlterField(
            model_name='info',
            name='email1',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='Эл. адрес 1'),
        ),
        migrations.AlterField(
            model_name='info',
            name='email2',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='Эл. адрес 2'),
        ),
        migrations.AlterField(
            model_name='info',
            name='phone1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Тел 1'),
        ),
        migrations.AlterField(
            model_name='info',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Тел 2'),
        ),
        migrations.AlterField(
            model_name='infotranslation',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='infotranslation',
            name='schedule1',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Рабочее расписание 1'),
        ),
        migrations.AlterField(
            model_name='infotranslation',
            name='schedule2',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Рабочее расписание 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='Каталог'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_img',
            field=models.ImageField(upload_to='product_pics', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='productimgs',
            name='img',
            field=models.ImageField(upload_to='product_pics', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productimgs',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='producttranslation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_img',
            field=models.ImageField(upload_to='', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='projectimgs',
            name='img',
            field=models.ImageField(upload_to='project_pics', verbose_name='картина'),
        ),
        migrations.AlterField(
            model_name='projectimgs',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project', verbose_name='проект'),
        ),
        migrations.AlterField(
            model_name='projecttranslation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='projecttranslation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='projecttranslation',
            name='text',
            field=models.TextField(verbose_name='Основная часть статьи'),
        ),
    ]
