# Generated by Django 4.0.3 on 2022-03-12 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='characteristictranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='characteristictranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='Characteristic',
        ),
        migrations.DeleteModel(
            name='CharacteristicTranslation',
        ),
    ]
